# Generated by Django 5.2.4 on 2025-07-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_in_user_library', to='bookscaner.book'),
        ),
    ]
