# Generated by Django 5.2.4 on 2025-07-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0004_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(blank=True, related_name='book_in_user_library', to='bookscaner.book'),
        ),
    ]
