# Generated by Django 5.2.4 on 2025-07-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0005_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_src',
            field=models.CharField(blank=True),
        ),
    ]
