# Generated by Django 5.2.4 on 2025-07-30 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0006_book_image_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='timestamp',
            new_name='published_date',
        ),
    ]
