# Generated by Django 5.2.4 on 2025-07-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0007_rename_timestamp_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
            preserve_default=False,
        ),
    ]
