# Generated by Django 5.2.4 on 2025-07-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0008_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
