# Generated by Django 5.2.4 on 2025-07-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0010_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_src',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
