# Generated by Django 5.2.4 on 2025-08-01 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0011_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Reading')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_book_status', to='bookscaner.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
