# Generated by Django 5.2.4 on 2025-08-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookscaner', '0013_alter_bookstatus_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
